[package]
name = "esmeralda-bin"
version = "1.5.0"
edition = "2021"
description = "The purpose of the Emerald is to help control spending and money, knowing where the money goes, how much can be spent, who made the debt and the total of that debt."
resolver = "2"
license = "MIT"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
async-trait = "0.1"
esmeralda-services = { path = "../esmeralda-services" }
esmeralda-apis = { path = "../esmeralda-apis" }
esmeralda-cryptography = { path = "../cryptography" }
esmeralda-database = { path = "../database" }
esmeralda-debt = { path = "../debt" }
esmeralda-entities = { path = "../entities" }
esmeralda-file-export = { path = "../file-export" }
esmeralda-views = { path = "../esmeralda-views" }
