[package]
name = "esmeralda"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
deadpool-postgres = "0.11.0"
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
dioxus-html = "0.4.3"
dioxus-router = "0.4.3"
lazy_static = "1.4.0"
postgres = "0.19.7"
rand = "0.8.5"
rust-crypto = "0.2.36"
serde = {version = "1.0.193", features = ["derive"]}
thiserror = "1.0.50"
tokio = "1.34.0"

