[package]
name = "esmeralda-entities"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
esmeralda-database = { version = "1.5.0", path = "../database" }
serde = { workspace = true, features = ["serde_derive"] }
thiserror.workspace = true
uuid = { version = "1.19.0", features = ["v4"] }
