[package]
name = "esmeralda-database"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono.workspace = true
serde_json = "1.0"
esmeralda-entities = { path = "../entities" }
uuid.workspace = true
async-trait = "0.1"

[dev-dependencies]
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
